name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: '23'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build Java application
        run: mvn clean package

      - name: Extract Version Type from Commit Message
        id: extract_version
        run: |
          VERSION_TYPE=$(git log -1 --pretty=%B | grep -Eo 'major|minor|patch' || echo 'patch')
          echo "VERSION_TYPE=${VERSION_TYPE}"
          echo "VERSION_TYPE=${VERSION_TYPE}" >> $GITHUB_ENV

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          chmod +x ./push_image.sh
          ./push_image.sh ${{ env.VERSION_TYPE }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
